import pandas as pd
import numpy as np
import yfinance as yf
import pandas_ta as ta

class DataLoader:

    def __init__(self, tickers: list, start_date: str, end_date: str):
  
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.data = pd.DataFrame()

    def fetch_data(self) -> pd.DataFrame:
 
        try:
            # Download OHLCV data
            df = yf.download(self.tickers, start=self.start_date, end=self.end_date)
            
            # If a single ticker is passed, yf returns a MultiIndex or DataFrame depending on version.
            # We want to ensure we have a standard format.
            if len(self.tickers) == 1:
                # yfinance >= 0.2.0 returns a DataFrame with ticker as top level if not careful
                if isinstance(df.columns, pd.MultiIndex):
                    df.columns = df.columns.get_level_values(0)
                
            # Drop any rows where OHLC is missing
            self.data = df.dropna(subset=['Close'])
            print(f"Data fetched successfully. Columns: {list(self.data.columns)}")
            return self.data
            
        except Exception as e:
            print(f"Error fetching data: {e}")
            return pd.DataFrame()

    def engineer_features(self, ticker: str, vol_window: int = 21, ma_fast: int = 50, ma_slow: int = 200) -> pd.DataFrame:
    
        # If data is multi-indexed (multiple tickers), slice the ticker first
        if isinstance(self.data.columns, pd.MultiIndex):
            df = self.data.xs(ticker, axis=1, level=1).copy()
        else:
            df = self.data.copy()
            
        # Ensure standard column names
        df.rename(columns={'Close': 'Price'}, inplace=True)
        
        # 1. Daily Log Returns
        df['Log_Return'] = np.log(df['Price'] / df['Price'].shift(1))
        # Smooth returns for better regime state persistence
        df['Return_SMA_5'] = df['Log_Return'].rolling(window=5).mean()
        
        # 2. Realized Volatility (Annualized)
        df['Volatility'] = df['Log_Return'].rolling(window=vol_window).std() * np.sqrt(252)
        
        # 3. Moving Average Trend Ratios
        df[f'MA_{ma_fast}'] = df['Price'].rolling(window=ma_fast).mean()
        df[f'MA_{ma_slow}'] = df['Price'].rolling(window=ma_slow).mean()
        df['Trend_Ratio'] = df[f'MA_{ma_fast}'] / df[f'MA_{ma_slow}']
        
        # 4. Bear Market Detector: Log Drawdown from 252-day High
        rolling_max = df['Price'].rolling(window=252, min_periods=1).max()
        df['Log_Drawdown'] = np.log(df['Price'] / rolling_max)
        
        # 5. COMPLEX FEATURES
        
        # A. RSI (Momentum)
        df['RSI'] = ta.rsi(df['Price'], length=14)
        
        # B. Bollinger Band Width (Vol Squeeze detector)
        bbands = ta.bbands(df['Price'], length=20, std=2)
        if bbands is not None:
            # pandas_ta returns a 'BBB' (Bandwidth) column automatically
            # We look for the one starting with BBB_
            bbb_col = [c for c in bbands.columns if c.startswith('BBB_')]
            if bbb_col:
                df['BB_Width'] = bbands[bbb_col[0]]
            else:
                # Fallback calculation if the column naming is unexpected
                df['BB_Width'] = (bbands.iloc[:, 2] - bbands.iloc[:, 0]) / bbands.iloc[:, 1]
        
        # C. Higher-Order Moments (The "Fat Tail" Detectors)
        # Real markets display high Kurtosis and negative Skew in crashes
        df['Rolling_Skew_63'] = df['Log_Return'].rolling(window=63).skew()
        df['Rolling_Kurt_63'] = df['Log_Return'].rolling(window=63).kurt()
        
        # D. Volume Intensity (if Volume exists)
        if 'Volume' in df.columns:
            df['Vol_Ratio'] = df['Volume'] / df['Volume'].rolling(window=50).mean()
        
        # Drop NaN values generated by windows
        df.dropna(inplace=True)
        
        return df

if __name__ == "__main__":
    # Example usage
    loader = DataLoader(['SPY'], '2000-01-01', '2023-12-31')
    raw_data = loader.fetch_data()
    
    if not raw_data.empty:
        features = loader.engineer_features('SPY')
        print(f"\nEngineered Features Shape: {features.shape}")
        print("\nHead:")
        print(features.head())
        print("\nTail:")
        print(features.tail())
