import pandas as pd
import numpy as np
import yfinance as yf
import pandas_ta as ta

class DataLoader:

    def __init__(self, tickers: list, start_date: str, end_date: str):
  
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.data = pd.DataFrame()

    def fetch_data(self) -> pd.DataFrame:
 
        try:
            # Download adjusted close prices
            df = yf.download(self.tickers, start=self.start_date, end=self.end_date)['Close']
            
            # If a single ticker is passed, yf returns a Series. Convert to DataFrame.
            if isinstance(df, pd.Series):
                df = df.to_frame(name=self.tickers[0])
                
            # Drop any rows where all data is missing
            self.data = df.dropna(how='all')
            print("Data fetched successfully.")
            return self.data
            
        except Exception as e:
            print(f"Error fetching data: {e}")
            return pd.DataFrame()

    def engineer_features(self, ticker: str, vol_window: int = 21, ma_fast: int = 50, ma_slow: int = 200) -> pd.DataFrame:
    
        if ticker not in self.data.columns:
            raise ValueError(f"Ticker '{ticker}' not found in loaded data.")
            
        df = self.data[[ticker]].copy()
        df.rename(columns={ticker: 'Price'}, inplace=True)
        
        # 1. Daily Log Returns
        df['Log_Return'] = np.log(df['Price'] / df['Price'].shift(1))
        # Smooth returns for better regime state persistence
        df['Return_SMA_5'] = df['Log_Return'].rolling(window=5).mean()
        
        # 2. Realized Volatility (Annualized)
        # Standard deviation of log returns over the window, multiplied by sqrt(252)
        df['Volatility'] = df['Log_Return'].rolling(window=vol_window).std() * np.sqrt(252)
        
        # 3. Moving Averages
        df[f'MA_{ma_fast}'] = df['Price'].rolling(window=ma_fast).mean()
        df[f'MA_{ma_slow}'] = df['Price'].rolling(window=ma_slow).mean()
        
        # 4. Short-Term Trend Ratio (50 / 200)
        df['Trend_Ratio'] = df[f'MA_{ma_fast}'] / df[f'MA_{ma_slow}']
        
        # 5. Long-Term Trend Ratio (Price / 200)
        df['Trend_Ratio_Long'] = df['Price'] / df[f'MA_{ma_slow}']
        
        # 6. Bear Market Detector: Log Drawdown from 252-day High
        rolling_max = df['Price'].rolling(window=252, min_periods=1).max()
        df['Log_Drawdown'] = np.log(df['Price'] / rolling_max)
        
        # Drop NaN values generated by rolling windows and shifts
        df.dropna(inplace=True)
        
        return df

if __name__ == "__main__":
    # Example usage
    loader = DataLoader(['SPY'], '2000-01-01', '2023-12-31')
    raw_data = loader.fetch_data()
    
    if not raw_data.empty:
        features = loader.engineer_features('SPY')
        print(f"\nEngineered Features Shape: {features.shape}")
        print("\nHead:")
        print(features.head())
        print("\nTail:")
        print(features.tail())
